# Generated by Django 3.2.7 on 2021-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boswellCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='base',
            field=models.BooleanField(default=False),
        ),
    ]
