# Generated by Django 3.2.7 on 2021-09-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boswellCore', '0002_tag_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
