# Generated by Django 3.2.7 on 2021-09-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boswellCore', '0003_alter_tag_tag_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tag_text', 'entry')},
        ),
    ]
