# Generated by Django 3.2.7 on 2021-09-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boswellCore', '0004_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(max_length=255),
        ),
    ]
